=== api-evangelist/amazon-s3/json-schema/amazon-s3-tables-table-detail-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "TableDetail",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the table."
    },
    "tableARN": {
      "type": "string",
      "description": "The Amazon Resource Name (ARN) of the table."
    },
    "namespace": {
      "type": "array"
    },
    "versionToken": {
      "type": "string",
      "description": "The version token of the table."
    },
    "metadataLocation": {
      "type": "string",
      "description": "The S3 URI location of the table metadata."
    },
    "warehouseLocation": {
      "type": "string",
      "description": "The S3 URI of the warehouse location for the table."
    },
    "createdAt": {
      "type": "string"
    },
    "createdBy": {
      "type": "string"
    },
    "modifiedAt": {
      "type": "string"
    },
    "modifiedBy": {
      "type": "string"
    },
    "managedByService": {
      "type": "string"
    },
    "ownerAccountId": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "format": {
      "type": "string"
    }
  }
}

=== api-evangelist/amazon-s3/examples/amazon-s3-tables-table-detail-example.json
{
  "name": "Example Title",
  "tableARN": "example_value",
  "namespace": [],
  "versionToken": "example_value",
  "metadataLocation": "example_value",
  "warehouseLocation": "example_value",
  "createdAt": "example_value",
  "createdBy": "example_value",
  "modifiedAt": "example_value",
  "modifiedBy": "example_value",
  "managedByService": "example_value",
  "ownerAccountId": "500123",
  "type": "example_value",
  "format": "example_value"
}
